webapp/Tutorial/urls.py
from django.urls import path, include
from .views import *

app_name = 'Tutorial'
urlpatterns = [
    path('', HomeView, name = 'home'),
    path('login/', LoginView, name = 'login'),
    path('logout/', LogoutView, name = 'logout'),
    path('register/', registerView, name='register'),
    path('forum/',ForumView,name='forum'),
    path('forum/new/', ForumPostFormView, name = 'newForum'),
    path('forum/delete/<postid>/', ForumPostDeleteView, name = 'deleteForum'),
]

webapp/Tutorial/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View, TemplateView
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate, login, logout

from .models import *
from .forms import *

# Create your views here.
def HomeView(request):
    return render(request, 'home.html')

def LoginView(request):
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        if next:
            return redirect(next)
        return redirect('/')

    context = {
        'form': form,
    }
    return render(request, "login.html", context)

def LogoutView(request):
    logout(request)
    return redirect('/')

def registerView(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = UserForm()
    return render(request, 'signup.html', {'form': form})

def ForumView(request):
    user = request.user
    ForumPosts =  ForumPost.objects.all()
    #print(ForumPosts)
    context = {'posts': ForumPosts, 'user': user,}
    return render(request, 'ForumPost.html', context)

def ForumPostFormView(request):
    form = ForumPostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.user = request.user
        post.save()
        return redirect('Tutorial:forum')
    context = {'form': form, 'title': 'New Post',}
    return render(request, "NewForumPost.html", context)

def ForumPostDeleteView(request, postid):
    post = ForumPost.objects.get(pk = postid)
    post.delete()
    return redirect('/forum/')

webapp/Tutorial/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'Tutorial/css/style.css' %}">
    <title>Web App Tutorial</title>
</head>
<body>
<nav class="navbar navbar-expand-md fixed-top">
      <a class="navbar-brand" href="{% url 'Tutorial:home' %}">TU Happening</a>
      <div class="collapse navbar-collapse order-3" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
              <li class = "nav-item">
                <a class = "nav-link" href="#">Profile<span class="sr-only">(current)</span></a>
              </li>
          <li class = "nav-item">
            <a class = "nav-link" href="{% url 'Tutorial:logout' %}">Logout<span class="sr-only">(current)</span></a>
          </li>
          {% else %}
          <li class = "nav-item">
            <a class = "nav-link" href="{% url 'Tutorial:login' %}">Login<span class="sr-only">(current)</span></a>
          </li>
          <li class = "nav-item">
            <a class = "nav-link" href="{% url 'Tutorial:register' %}">Register<span class="sr-only">(current)</span></a>
          </li>
          {% endif %}
          <li class = "nav-item">
            <a class = "nav-link" href="{% url 'Tutorial:forum' %}">Forum<span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
    </nav>
<main class = "main">
    {% block main %}

    {% endblock %}
</main>

<footer class="footer fixed-bottom">
Scott Glascott
</footer>
</body>
</html>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

webapp/Tutorial/templates/home.html
{% extends 'base.html' %}

{% block main %}
<div class = "container-fluid">
    <div id = "home">
    <img id="banner" src="static/Tutorial/img/banner.png">
    <p>
        The Temple University bulletin called TUHappening will 
        allow students to publicly or anonymously discuss topics 
        about everything Temple. Students can talk about classes, 
        news, sports, clubs, faculty, services, or anything else 
        they might want to discuss. It is an open forum to Temple 
        Students only! Students can create new topics to talk about 
        or find other topics to talk to students about. Clubs on
        campus can advertise events, students can discuss classes 
        or the professors that run them, chat about <a 
            href="http://www.ratemyprofessors.com/campusRatings.jsp?sid=999">
            Rate My Professor</a> rankings, or comment on local 
        eats and bars! Sign up today to see what your peers think 
        about the community around you.
    </p>
    </div>
</div>
{% endblock main %}

webapp/Tutorial/templates/login.html
{% extends 'base.html' %}


{% block main %}
  <h2>Login</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" />
    </form>
{% endblock %}

webapp/Tutorial/templates/register.html
{% extends 'base.html' %}
{% block main %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Create a new Account</h3>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}