ebdjango/webapp/Tutorial/urls.py
from django.urls import path, include
from .views import *

app_name = 'Tutorial'
urlpatterns = [
    path('', HomeView, name = 'home'),
    #path('login/', LoginView, name = 'login'),
    #path('logout/', LogoutView, name = 'logout'),
    path('register/', UserFormView.as_view(), name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path("profile/", ProfileView, name = "profilePage"),
    path('forum/',ForumView,name='forum'),
    path('forum/new/', ForumPostFormView, name = 'newForum'),
    path('forum/delete/<postid>/', ForumPostDeleteView, name = 'deleteForum'),
]

ebdjango/webapp/webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from webapp import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Tutorial.urls'), name='home'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ebdjango/webapp/Tutorial/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User

class ForumPost(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    postTitle = models.CharField(max_length = 100)
    postBody = models.CharField(max_length = 1000)
    postDate = models.DateField(default=timezone.now)
    
    def __str__(self):
        return self.postTitle

ebdjango/webapp/Tutorial/forms.py
from django.contrib.auth.models import User
from django.contrib.auth import (authenticate, get_user_model)
from django import forms
from .models import *

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']


User = get_user_model()


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('This user does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect password')
            if not user.is_active:
                raise forms.ValidationError('This user is not active')
        return super(UserLoginForm, self).clean(*args, **kwargs)

class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label='Email address')
    email2 = forms.EmailField(label='Confirm Email')
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'email2',
            'password'
        ]

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')
        if email != email2:
            raise forms.ValidationError("Emails must match")
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError(
                "This email has already been registered")
        return super(UserRegisterForm, self).clean(*args, **kwargs)

class ForumPostForm(forms.ModelForm):
    class Meta:
        model = ForumPost
        fields = [
            'postTitle',
            'postBody',
        ]

ebdjango/webapp/Tutorial/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View, TemplateView
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from .models import *
from .forms import *

# Create your views here.
def HomeView(request):
    return render(request, 'home.html')

def LoginView(request):
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        if next:
            return redirect(next)
        return redirect('/')

    context = {
        'form': form,
    }
    return render(request, "login.html", context)

def LogoutView(request):
    logout(request)
    return redirect('/')

class UserFormView(View):
    form_class = UserForm
    template_name = 'register.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('Tutorial:home')
        return render(request, self.template_name, {'form': form})

def ForumView(request):
    user = request.user
    ForumPosts =  ForumPost.objects.all()
    #print(ForumPosts)
    context = {'posts': ForumPosts, 'user': user,}
    return render(request, 'ForumPost.html', context)

def ForumPostFormView(request):
    if request.user.is_anonymous:
        messages.info(request, "You must be logged in to make a post!")
        return redirect('Tutorial:login')
    form = ForumPostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.user = request.user
        post.save()
        return redirect('Tutorial:forum')
    context = {'form': form, 'title': 'New Post',}
    return render(request, "NewForumPost.html", context)

def ForumPostDeleteView(request, postid):
    post = ForumPost.objects.get(pk = postid)
    post.delete()
    return redirect('/forum/')

def ProfileView(request):
    user = request.user
    context = {'user': user}
    return render(request, "profile.html", context)

ebdjango/webapp/Tutorial/templates/ForumPost.html
{% extends 'base.html' %}
{% block main %}

    <div class = "table-responsive">
        <table class = "table table-striped">
            <thead>
                <tr>
                    {% if request.user.is_staff %}
                        <th>ID</th>
                    {% endif %}
                    <th>Title</th>
                    <th>Body</th>
                    <th>Date</th>
                    <th>User</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                <tr>
                    {% if request.user.is_staff %}
                    <td>{{post.id}}</td>
                    {% endif %}
                    <td>{{post.postTitle}}</td>
                    <td>{{post.postBody}}</td>
                    <td>{{post.postDate}}</td>
                    <td>{{post.user}}</td>
                    {% if request.user.is_staff %}
                    <td><a href = "/forum/delete/{{post.id}}/" class = "btn btn-danger">X</a></td>
                    {% endif %}
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <a href = "{% url 'Tutorial:newForum' %}" class = "btn btn-md"> New Post </a>

{% endblock main %}

ebdjango/webapp/Tutorial/templates/NewForumPost.html
{% extends 'base.html' %}
{% block main %}

    <h1>{{title}}</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" />
    </form>
{% endblock main %}

ebdjango/webapp/Tutorial/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'Tutorial/css/style.css' %}">
    <title>Web App Tutorial</title>
</head>
<body>
<nav class="navbar navbar-expand-md fixed-top">
      <a class="navbar-brand" href="{% url 'Tutorial:home' %}">TU Happening</a>
      <div class="collapse navbar-collapse order-3" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
              <li class = "nav-item">
                <a class = "nav-link" href="{% url 'Tutorial:profilePage' %}">Profile<span class="sr-only">(current)</span></a>
              </li>
          <li class = "nav-item">
            <a class = "nav-link" href="{% url 'Tutorial:logout' %}">Logout<span class="sr-only">(current)</span></a>
          </li>
          {% else %}
          <li class = "nav-item">
            <a class = "nav-link" href="{% url 'Tutorial:login' %}">Login<span class="sr-only">(current)</span></a>
          </li>
          <li class = "nav-item">
            <a class = "nav-link" href="{% url 'Tutorial:register' %}">Register<span class="sr-only">(current)</span></a>
          </li>
          {% endif %}
          <li class = "nav-item">
            <a class = "nav-link" href="{% url 'Tutorial:forum' %}">Forum<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="http://cis-linux2.temple.edu:8080/FA18_3308_tuf01128/">Return<span class="sr-only">(current)</span></a>
        </ul>
      </div>
    </nav>
<main class = "main">
    {% block main %}

    {% endblock %}
</main>

<footer class="footer fixed-bottom">
Scott Glascott
</footer>
</body>
</html>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

ebdjango/webapp/Tutorial/templates/form-template.html
{% extends 'base.html' %}

{% block main %}
  <h2>Sign up</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" />
    </form>
{% endblock %}

ebdjango/webapp/Tutorial/templates/home.html
{% extends 'base.html' %}

{% block main %}
{% load static %}
<div class = "container-fluid">
    <div id = "home">
    <img id="banner" src="static/Tutorial/img/banner.png">
    <h1 id = "homeH1">Django Web Applications</h1>
    <p>
        Welcome to my Django web Application Tutorial! Django is a modern web framework written in python and used by many large companies today such as Instagram, YouTube, Spotify, and Dropbox. 
        The purpose of this tutorial is to demonstrate how you might implement what you have learned this semester in a modern web framework. To begin, 
        you need to have the latest version of python and an IDE to work in. You will then need to have a virtual environment with Django installed. 
        This will be your working environment for your project.
    </p>
    <h2>Architecture</h2>
    <p>
         The Django web framework is sitting in the backend waiting for a user to make a URL request. When the request is received the URL Dispatcher 
         determines which View to load. A View is a python function that generates a web response. Views handle all of the mechanics of your webpages. 
         A View can be as simple as returning a simple HTML page, or it can do something more complex like fetch data from the database, load it into a 
         dynamic HTML page, and then return it to the user. If the view accesses the database, it will do so through Django Models. Django handles all 
         communication between the server and the Database. A Model is a class that represents a Table in your database. When Models are created, you 
         initialize them with their appropriate data types.  When the server retrieves the data from the database, it uses the Model to turn the data 
         into an object which can then be used by the Views. 
    </p>
    <h2>URL Dispatcher</h2>
    <p>
        As discussed earlier, the URL Dispatcher determine which View is executed in order to return a response to the user. You create a path by 
        designating a URL path, the view to be called, and then you can assign the path a name to be referenced in other functions.
        <div class="card">
        <div class="card-body">
        <pre><code>
            from django.urls import path, include
            from .views import *

            app_name = 'Tutorial'
            urlpatterns = [
                path('', HomeView, name = 'home'),
                path('login/', LoginView, name = 'login'),
                path('logout/', LogoutView, name = 'logout'),
                path('register/', registerView, name='register'),
                path('forum/',ForumView,name='forum'),
                path('forum/new/', ForumPostFormView, name = 'newForum'),
                path('forum/delete/', ForumPostDeleteView, name = 'deleteForum'),
            ]
        </code></pre></div></div>
    </p>

    <h2>Views</h2>
    <p>
        Views are the core functionality of your Django web applications. An example of a simple View would be the following 
        function used to return the home page:
        <div class="card">
        <div class="card-body">
        <pre><code>
            def HomeView(request):
                return render(request, 'home.html')
        </code></pre></div></div>
    </p>
    <p>
        Views can also be used to display data using Models and Forms. This example first takes stores the built in user model from the 
        request, similar to our session handling with JSP pages, and stores it into a variable labeled “user.”  It then retrieves all of 
        the stored ForumPost models using the objects.all() function. This Model will be discussed more in depth later. The all() method 
        generates a query specific to your object and will return a query set of all objects returned. This query set can be parsed into 
        any data structure a developer might need.  I then create a dictionary associating the variables with keys to be sent to your HTML 
        template.  Finally you return your rendered HTML template with your request and dictionary data. 
        <div class="card">
        <div class="card-body">
        <pre><code>
        def ForumView(request):
            user = request.user
            ForumPosts =  ForumPost.objects.all()
            #print(ForumPosts)
            context = {'posts': ForumPosts, 'user': user,}
            return render(request, 'ForumPost.html', context)
        </code></pre></div></div>
    </p>
    <p>
        Views are also used for requests that simply add or delete entries in the database. To save information, you retrieve the data from 
        your HTML form, then you prepare the data to be committed, and then use the save() function to save the data:
        <div class="card">
        <div class="card-body">
        <pre><code>
            def ForumPostFormView(request):
                form = ForumPostForm(request.POST or None)
                if form.is_valid():
                    post = form.save(commit=False)
                    post.user = request.user
                    post.save()
                    return redirect('Tutorial:forum')
                context = {'form': form, 'title': 'New Post',}
                return render(request, "NewForumPost.html", context)
        </code></pre></div></div>
    </p>
    <p>
        To delete an entry, you simply retrieve the object using some searching criteria, in this case we use the primary 
        key which we send through requests. Then we use the delete() function on the object and return to a page. In this case we return 
        to the original page which simply acts as a refresh to see that the data has been deleted.
        <div class="card">
        <div class="card-body">
        <pre><code>
            def ForumPostDeleteView(request, postid):
                post = ForumPost.objects.get(pk = postid)
                post.delete()
                return redirect('/forum/')
        </code></pre></div></div>
    </p>

    <h2>Models</h2>
    <p>
        As discussed previously Models are objects that are used to manage database entries. Each Model represents one table in the database. 
        Each Model contains the attributes which are the fields in the table. They are then initialized by assigning a database datatype to it.
        For this example we use the Forum Posts which store all of the posts by users. We have our user field which is a foreign key to the built 
        in User object. This is used to keep track of each user’s posts and when working with the ForumPost Model we can also access all 
        attributes of the User object. It also stores the title and body as char fields with varying max lengths. And finally it stores the 
        date of the post which is auto filled to the current date. 
        <div class="card">
        <div class="card-body">
        <pre><code>
            class ForumPost(models.Model):
                user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
                postTitle = models.CharField(max_length = 100)
                postBody = models.CharField(max_length = 1000)
                postDate = models.DateField(default=timezone.now)
                
                def __str__(self):
                    return self.postTitle
        </code></pre></div></div>
    <p>

    <h2>HTML Templates</h2>
    <p>
        HTML Templates are Django’s way of rendering dynamic HTML pages. Using various symbols and key words we can inject python into our 
        HTML pages to build dynamic pages. For our projects we used ajax calls to render the content of our web pages. We can do this in Django 
        by using the “extends” and “block” functions. For example, we have our base.html file which contains our header, navbar, footer, and a 
        “block” called “main.” Here is a simple example of what this may look like, , unfortunatly due to the nature of these files, 
        I must import a picture instead of a live code example:
        </p>
        <img id="codeImg" src="{% static 'Tutorial/img/baseExample.png' %}"/>

        <p>
        We can then populate this main block by writing a new HTML file that extends our base. We then open the block and populate it with any 
        information we want. Pages can have multiple blocks and you can have chains of extension that cascade all the way to the top. Here 
        is an example of a content file:
        </p>
        <img id="codeImg" src="static/Tutorial/img/extendExample.png">
        

        <p>
        You can also use templates to inject python that would allow you to build tables, charts, or graphs of various sizes. For this project 
        I use this method to write a for loop that will build the forum page. The view sends a list of post objects to the template, then the 
        for loop iterates through this list and builds a row in a table for each entry. Here is what that code looks like, note the extension 
        and block as well:
        </p>
        <img id="codeImg" src="static/Tutorial/img/forumCode.png">
        
    <h2>Project Code</h2>
    <p>
    <a class="btn btn-primary" href="https://github.com/SGlascott/WebAppTutorial" role="button">Check out the project on GitHub!</a></p>
    </div>
</div>
{% endblock main %}

ebdjango/webapp/Tutorial/templates/profile.html
{% extends 'base.html' %}
{% block main %}

    <ul>
        <li>Username: {{user.username}} </li>
        <li>Email: {{user.email}}</li>
        <li>First Name: {{user.first_name}}</li>
        <li>Last Name: {{user.last_name}}</li>
    </ul>

{% endblock %}

ebdjango/webapp/Tutorial/templates/register.html
{% extends 'base.html' %}
{% block main %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Create a new Account</h3>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'form-template.html' %}
                            <div class="form-group">
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

ebdjango/webapp/Tutorial/templates/signup.html
{% extends 'base.html' %}

{% block main %}
  <h2>Sign up</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" />
    </form>
{% endblock %}